'use strict';
const DEFAULT_BACKEND_URL='https://script.google.com/macros/s/AKfycbwXO7MK9U_59iEQ702-2JVKO348tDq6TCPsyDxw0nJnry6GDaKAxYy98ApHTBzmp3OJ/exec';
const TEACHER_PIN='45612378';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const pronouns=['yo','tú','él/ella','nosotros/as','vosotros/as','ellos/as'];
const people=['1.ª persona singular','2.ª persona singular','3.ª persona singular','1.ª persona plural','2.ª persona plural','3.ª persona plural'];
const tenses=[
{id:'presente',name:'Presente'}, {id:'preterito',name:'Pretérito perfecto simple'}, {id:'imperfecto',name:'Pretérito imperfecto'}, {id:'futuro',name:'Futuro simple'}, {id:'condicional',name:'Condicional simple'}, {id:'perfecto',name:'Pretérito perfecto compuesto'}
];
const verbs=[
{inf:'cantar',group:'-ar regular',tip:'Los verbos acabados en -ar mantienen la raíz y cambian la terminación.',forms:{presente:['canto','cantas','canta','cantamos','cantáis','cantan'],preterito:['canté','cantaste','cantó','cantamos','cantasteis','cantaron'],imperfecto:['cantaba','cantabas','cantaba','cantábamos','cantabais','cantaban'],futuro:['cantaré','cantarás','cantará','cantaremos','cantaréis','cantarán'],condicional:['cantaría','cantarías','cantaría','cantaríamos','cantaríais','cantarían'],perfecto:['he cantado','has cantado','ha cantado','hemos cantado','habéis cantado','han cantado']}},
{inf:'comer',group:'-er regular',tip:'En -er fíjate en las terminaciones: como, comes, come, comemos...',forms:{presente:['como','comes','come','comemos','coméis','comen'],preterito:['comí','comiste','comió','comimos','comisteis','comieron'],imperfecto:['comía','comías','comía','comíamos','comíais','comían'],futuro:['comeré','comerás','comerá','comeremos','comeréis','comerán'],condicional:['comería','comerías','comería','comeríamos','comeríais','comerían'],perfecto:['he comido','has comido','ha comido','hemos comido','habéis comido','han comido']}},
{inf:'vivir',group:'-ir regular',tip:'Los verbos -ir se parecen a los -er, pero nosotros y vosotros cambian: vivimos, vivís.',forms:{presente:['vivo','vives','vive','vivimos','vivís','viven'],preterito:['viví','viviste','vivió','vivimos','vivisteis','vivieron'],imperfecto:['vivía','vivías','vivía','vivíamos','vivíais','vivían'],futuro:['viviré','vivirás','vivirá','viviremos','viviréis','vivirán'],condicional:['viviría','vivirías','viviría','viviríamos','viviríais','vivirían'],perfecto:['he vivido','has vivido','ha vivido','hemos vivido','habéis vivido','han vivido']}},
{inf:'ser',group:'irregular esencial',tip:'Ser es irregular. Se usa para identidad, características y origen.',forms:{presente:['soy','eres','es','somos','sois','son'],preterito:['fui','fuiste','fue','fuimos','fuisteis','fueron'],imperfecto:['era','eras','era','éramos','erais','eran'],futuro:['seré','serás','será','seremos','seréis','serán'],condicional:['sería','serías','sería','seríamos','seríais','serían'],perfecto:['he sido','has sido','ha sido','hemos sido','habéis sido','han sido']}},
{inf:'estar',group:'irregular esencial',tip:'Estar indica estado, lugar o situación.',forms:{presente:['estoy','estás','está','estamos','estáis','están'],preterito:['estuve','estuviste','estuvo','estuvimos','estuvisteis','estuvieron'],imperfecto:['estaba','estabas','estaba','estábamos','estabais','estaban'],futuro:['estaré','estarás','estará','estaremos','estaréis','estarán'],condicional:['estaría','estarías','estaría','estaríamos','estaríais','estarían'],perfecto:['he estado','has estado','ha estado','hemos estado','habéis estado','han estado']}},
{inf:'tener',group:'irregular',tip:'Tener cambia: tengo, tienes. En futuro y condicional usa tendr-.',forms:{presente:['tengo','tienes','tiene','tenemos','tenéis','tienen'],preterito:['tuve','tuviste','tuvo','tuvimos','tuvisteis','tuvieron'],imperfecto:['tenía','tenías','tenía','teníamos','teníais','tenían'],futuro:['tendré','tendrás','tendrá','tendremos','tendréis','tendrán'],condicional:['tendría','tendrías','tendría','tendríamos','tendríais','tendrían'],perfecto:['he tenido','has tenido','ha tenido','hemos tenido','habéis tenido','han tenido']}},
{inf:'hacer',group:'irregular',tip:'Hacer tiene formas especiales: hago, hice. En futuro aparece har-.',forms:{presente:['hago','haces','hace','hacemos','hacéis','hacen'],preterito:['hice','hiciste','hizo','hicimos','hicisteis','hicieron'],imperfecto:['hacía','hacías','hacía','hacíamos','hacíais','hacían'],futuro:['haré','harás','hará','haremos','haréis','harán'],condicional:['haría','harías','haría','haríamos','haríais','harían'],perfecto:['he hecho','has hecho','ha hecho','hemos hecho','habéis hecho','han hecho']}},
{inf:'ir',group:'irregular esencial',tip:'Ir es muy irregular. En pretérito comparte formas con ser.',forms:{presente:['voy','vas','va','vamos','vais','van'],preterito:['fui','fuiste','fue','fuimos','fuisteis','fueron'],imperfecto:['iba','ibas','iba','íbamos','ibais','iban'],futuro:['iré','irás','irá','iremos','iréis','irán'],condicional:['iría','irías','iría','iríamos','iríais','irían'],perfecto:['he ido','has ido','ha ido','hemos ido','habéis ido','han ido']}},
{inf:'decir',group:'irregular',tip:'Decir cambia a digo y en futuro usa dir-.',forms:{presente:['digo','dices','dice','decimos','decís','dicen'],preterito:['dije','dijiste','dijo','dijimos','dijisteis','dijeron'],imperfecto:['decía','decías','decía','decíamos','decíais','decían'],futuro:['diré','dirás','dirá','diremos','diréis','dirán'],condicional:['diría','dirías','diría','diríamos','diríais','dirían'],perfecto:['he dicho','has dicho','ha dicho','hemos dicho','habéis dicho','han dicho']}},
{inf:'poder',group:'irregular',tip:'Poder alterna o/ue: puedo, puedes. En futuro usa podr-.',forms:{presente:['puedo','puedes','puede','podemos','podéis','pueden'],preterito:['pude','pudiste','pudo','pudimos','pudisteis','pudieron'],imperfecto:['podía','podías','podía','podíamos','podíais','podían'],futuro:['podré','podrás','podrá','podremos','podréis','podrán'],condicional:['podría','podrías','podría','podríamos','podríais','podrían'],perfecto:['he podido','has podido','ha podido','hemos podido','habéis podido','han podido']}},
{inf:'jugar',group:'irregular leve',tip:'Jugar cambia u/ue: juego, juegas, juega. Pero nosotros: jugamos.',forms:{presente:['juego','juegas','juega','jugamos','jugáis','juegan'],preterito:['jugué','jugaste','jugó','jugamos','jugasteis','jugaron'],imperfecto:['jugaba','jugabas','jugaba','jugábamos','jugabais','jugaban'],futuro:['jugaré','jugarás','jugará','jugaremos','jugaréis','jugarán'],condicional:['jugaría','jugarías','jugaría','jugaríamos','jugaríais','jugarían'],perfecto:['he jugado','has jugado','ha jugado','hemos jugado','habéis jugado','han jugado']}},
{inf:'leer',group:'irregular leve',tip:'En pretérito aparecen formas con y: leyó, leyeron.',forms:{presente:['leo','lees','lee','leemos','leéis','leen'],preterito:['leí','leíste','leyó','leímos','leísteis','leyeron'],imperfecto:['leía','leías','leía','leíamos','leíais','leían'],futuro:['leeré','leerás','leerá','leeremos','leeréis','leerán'],condicional:['leería','leerías','leería','leeríamos','leeríais','leerían'],perfecto:['he leído','has leído','ha leído','hemos leído','habéis leído','han leído']}}
];
const zones=[{xp:0,emoji:'🏡',name:'Villa Raíz',desc:'Primeros pasos'},{xp:80,emoji:'🌿',name:'Bosque Presente',desc:'Dominio del presente'},{xp:180,emoji:'🏰',name:'Castillo Pasado',desc:'Pretéritos en marcha'},{xp:320,emoji:'🚀',name:'Puerto Futuro',desc:'Formas futuras'},{xp:520,emoji:'🐉',name:'Cueva Irregular',desc:'Irregulares esenciales'}];
const badgeCatalog=[{id:'first',icon:'🌟',name:'Primer reto'},{id:'streak5',icon:'🔥',name:'Racha x5'},{id:'streak10',icon:'⚡',name:'Racha x10'},{id:'xp100',icon:'💎',name:'100 XP'},{id:'irregular10',icon:'🐉',name:'Domador irregular'},{id:'exam80',icon:'📝',name:'Evaluación sólida'}];
const avatars=['🦉','🦊','🐢','🐧','🦁','🐸','🐼','🐱','🐶','🦄','🐙','🦋','🐳','🐨','🐯'];
const DEFAULT_GROUPS=['5.ºA','5.ºB','6.ºA','6.ºB'];
let settings=loadJSON('verbopolis-settings',{backendUrl:DEFAULT_BACKEND_URL,classCode:'',accessible:false,quiet:false});
let groups=loadJSON('verbopolis-groups',DEFAULT_GROUPS);
let students=loadJSON('verbopolis-students',[]);
let missions=loadJSON('verbopolis-missions',{});
let queue=loadJSON('verbopolis-sync-queue',[]);
let state=null,currentQuestion=null,game=null;
let teacherUnlocked=sessionStorage.getItem('verbopolis-teacher-unlocked')==='1';
function boot(){ensureDemoData();applySettings();bindEvents();fillSelects();renderLogin();renderTeacherLockUi();}
function ensureDemoData(){if(!students.length){students=[{id:id(),name:'Alumno/a de prueba',group:'5.ºA',avatar:'🦉'}];saveJSON('verbopolis-students',students)}}
function bindEvents(){
 $('#addStudentBtn').onclick=addStudent; $('#newStudentName').addEventListener('keydown',e=>{if(e.key==='Enter')addStudent()}); $('#loginGroupFilter').onchange=renderLogin; $('#teacherLoginBtn').onclick=()=>{if(requestTeacherAccess())showTeacherFromLogin()};
 $$('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view))); $$('.tab').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view))); $('#switchStudentBtn').onclick=switchStudent;
 $('#verbSelect').onchange=renderStudy; $('#tenseSelect').onchange=renderStudy; $('#memoryMode').onchange=renderStudy; $('#toggleIrregular').onclick=()=>$('#verbTip').classList.toggle('hidden'); $('#speakTable').onclick=speakCurrentTable;
 $$('.mode').forEach(b=>b.onclick=()=>startGame(b.dataset.mode,false)); $('#practiceMistakes').onclick=()=>startGame('mixed',true); $('#forceSyncBtn').onclick=()=>syncQueue(true);
 $('#exportAllCsv').onclick=exportAllCsv; $('#syncAllBtn').onclick=()=>syncQueue(true); $('#lockTeacherBtn').onclick=lockTeacherArea; $('#makeWorksheet').onclick=createWorksheet;
 $$('.teacher-nav').forEach(b=>b.onclick=()=>showTeacherPanel(b.dataset.teacherPanel)); $('#saveMissionBtn').onclick=saveMission; $('#addGroupBtn').onclick=addGroup; $('#saveBackendBtn').onclick=saveBackend; $('#testBackendBtn').onclick=testBackend; $('#clearBackendBtn').onclick=clearBackend; $('#accessibleToggle').onchange=saveAccessSettings; $('#quietToggle').onchange=saveAccessSettings;
}
function fillSelects(){ $('#verbSelect').innerHTML=verbs.map(v=>`<option value="${v.inf}">${v.inf} · ${v.group}</option>`).join(''); $('#tenseSelect').innerHTML=tenses.map(t=>`<option value="${t.id}">${t.name}</option>`).join(''); $('#missionTense').innerHTML='<option value="all">Todos</option>'+tenses.map(t=>`<option value="${t.id}">${t.name}</option>`).join(''); $('#missionVerbs').innerHTML=verbs.map(v=>`<option value="${v.inf}">${v.inf}</option>`).join(''); renderGroupOptions();}
function renderGroupOptions(){const opts=groups.map(g=>`<option>${escapeHtml(g)}</option>`).join(''); $('#newStudentGroup').innerHTML=opts; $('#missionGroup').innerHTML=opts; $('#loginGroupFilter').innerHTML='<option value="all">Todos los grupos</option>'+opts;}
function renderLogin(){const filter=$('#loginGroupFilter').value||'all'; const list=students.filter(s=>filter==='all'||s.group===filter); $('#studentGrid').innerHTML=list.map(s=>`<button class="student-card" data-student="${s.id}"><span>${s.avatar}</span><strong>${escapeHtml(s.name)}</strong><small>${escapeHtml(s.group||'Sin grupo')}</small></button>`).join('')||'<div class="callout">No hay alumnado en este grupo.</div>'; $$('.student-card').forEach(b=>b.onclick=()=>loginStudent(b.dataset.student)); $('#loginSyncState').textContent=settings.backendUrl?'☁️ Google Sheets configurado':'💾 Modo local';}
function addStudent(){const name=$('#newStudentName').value.trim(); if(!name)return; const s={id:id(),name,group:$('#newStudentGroup').value||groups[0],avatar:avatars[students.length%avatars.length]}; students.push(s); saveJSON('verbopolis-students',students); $('#newStudentName').value=''; renderLogin(); renderGroupStudentList(); queueEvent('student_created',{studentId:s.id,studentName:s.name,group:s.group,avatar:s.avatar});}
function loginStudent(studentId){const s=students.find(x=>x.id===studentId); if(!s)return; state=getStudentState(s.id); $('#loginScreen').classList.add('hidden'); $('#appShell').classList.remove('hidden'); showView('play'); renderAll(); queueEvent('login',{group:state.group}); syncQueue(false);}
function switchStudent(){state=null; $('#appShell').classList.add('hidden'); $('#loginScreen').classList.remove('hidden'); renderLogin();}
function getStudentState(idv){const s=students.find(x=>x.id===idv)||students[0]; const st=loadJSON('verbopolis-state-'+idv,null); return st||{id:s.id,name:s.name,group:s.group,avatar:s.avatar,xp:0,total:0,correct:0,streak:0,bestStreak:0,mistakes:[],log:[],badges:[],irregularCorrect:0,cloudSaves:0,lastSync:''};}
function saveState(){if(!state)return; const s=students.find(x=>x.id===state.id); if(s){state.name=s.name;state.group=s.group;state.avatar=s.avatar} checkBadges(); saveJSON('verbopolis-state-'+state.id,state);}
function renderAll(){if(!state)return; $('#playerName').textContent=state.name; $('#playerAvatar').textContent=state.avatar; $('#groupLabel').textContent=`${state.group||'Aula'} · Verbópolis`; const level=Math.floor(state.xp/100)+1; $('#playerLevel').textContent=`Nivel ${level} · ${level<3?'Aprendiz':level<6?'Explorador/a':'Maestro/a verbal'}`; $('#xpBar').style.width=(state.xp%100)+'%'; $('#xpText').textContent=`${state.xp} XP`; renderMissionHero(); renderMap(); renderMistakes(); renderBadges(); renderStats(); renderLog(); renderSyncPanel(); renderStudy();}
function renderMissionHero(){const m=missions[state.group]; if(m){$('#heroTitle').textContent=m.title||'Misión del grupo'; $('#heroDesc').textContent=`Hoy trabajas ${m.tense==='all'?'varios tiempos':tenseName(m.tense)} con ${m.rounds||10} preguntas.`; $('#dailyGoal').textContent=`Objetivo: ${m.target||80}% de acierto`; $('#dailyHint').textContent=`Modo: ${modeLabel(m.mode)} · Grupo ${state.group}`; $('#missionIcon').textContent='🎯'} else {$('#heroTitle').textContent='Conquista los tiempos verbales.'; $('#heroDesc').textContent='Aún no hay misión especial para tu grupo. Puedes entrenar libremente.'; $('#dailyGoal').textContent='Objetivo: 5 aciertos seguidos'; $('#dailyHint').textContent='Completa un reto mixto para sumar XP.'; $('#missionIcon').textContent='🎯'}}
function showView(idv){if(idv==='teacher'&&!teacherUnlocked){if(!requestTeacherAccess())return;} $$('.view').forEach(v=>v.classList.toggle('active',v.id===idv)); $$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===idv)); if(idv==='dashboard'){renderStats();renderLog();renderSyncPanel()} if(idv==='teacher'){renderTeacher();} renderTeacherLockUi();}
function requestTeacherAccess(){const code=prompt('Introduce el código de maestro/a'); if(code&&code.trim()===TEACHER_PIN){teacherUnlocked=true; sessionStorage.setItem('verbopolis-teacher-unlocked','1'); renderTeacherLockUi(); return true;} if(code!==null)alert('Código incorrecto.'); return false;}
function lockTeacherArea(){teacherUnlocked=false; sessionStorage.removeItem('verbopolis-teacher-unlocked'); renderTeacherLockUi(); showView('play');}
function renderTeacherLockUi(){const tab=$('.teacher-tab'); if(tab)tab.textContent=teacherUnlocked?'Maestro/a abierto':'🔒 Maestro/a';}
function showTeacherFromLogin(){const fake=students[0]; loginStudent(fake.id); showView('teacher');}
function showTeacherPanel(name){$$('.teacher-nav').forEach(b=>b.classList.toggle('active',b.dataset.teacherPanel===name)); $$('.teacher-panel').forEach(p=>p.classList.toggle('active',p.id==='teacher-'+name)); if(name==='overview')renderClassSummary(); if(name==='missions')renderMissions(); if(name==='groups')renderGroupStudentList(); if(name==='settings')renderSettings();}
function renderTeacher(){renderClassSummary();renderMissions();renderGroupStudentList();renderSettings();}
function renderSettings(){$('#backendUrlInput').value=settings.backendUrl||''; $('#classCodeInput').value=settings.classCode||''; $('#accessibleToggle').checked=!!settings.accessible; $('#quietToggle').checked=!!settings.quiet;}
function saveAccessSettings(){settings.accessible=$('#accessibleToggle').checked; settings.quiet=$('#quietToggle').checked; saveJSON('verbopolis-settings',settings); applySettings();}
function applySettings(){document.body.classList.toggle('accessible',!!settings.accessible); document.body.classList.toggle('quiet',!!settings.quiet);}
function saveBackend(){settings.backendUrl=$('#backendUrlInput').value.trim(); settings.classCode=$('#classCodeInput').value.trim(); saveJSON('verbopolis-settings',settings); renderSyncPanel(); alert('Conexión guardada.');}
function clearBackend(){settings.backendUrl=''; saveJSON('verbopolis-settings',settings); renderSettings(); renderSyncPanel();}
function testBackend(){if(!settings.backendUrl)return alert('No hay URL configurada.'); jsonp('ping',{},res=>alert('Conexión recibida: '+(res.status||'ok')),()=>alert('No se ha podido probar. Revisa la implementación /exec.'))}
function addGroup(){const g=$('#newGroupName').value.trim(); if(!g)return; if(!groups.includes(g))groups.push(g); saveJSON('verbopolis-groups',groups); $('#newGroupName').value=''; renderGroupOptions(); renderLogin(); renderGroupStudentList();}
function renderGroupStudentList(){const html=groups.map(g=>{const list=students.filter(s=>s.group===g);return `<div class="radar-item"><h3>${escapeHtml(g)} · ${list.length}</h3>${list.map(s=>`<p><strong>${s.avatar} ${escapeHtml(s.name)}</strong> <button class="ghost small" data-rename="${s.id}">Editar</button></p>`).join('')||'<small>Sin alumnos todavía.</small>'}</div>`}).join(''); $('#groupStudentList').innerHTML=`<div class="radar-grid">${html}</div>`; $$('[data-rename]').forEach(b=>b.onclick=()=>editStudent(b.dataset.rename));}
function editStudent(sid){const s=students.find(x=>x.id===sid); if(!s)return; const name=prompt('Nombre o alias',s.name)||s.name; const group=prompt('Grupo',s.group)||s.group; s.name=name.trim()||s.name; if(group.trim()){if(!groups.includes(group.trim()))groups.push(group.trim()); s.group=group.trim();} saveJSON('verbopolis-students',students); renderGroupOptions(); renderLogin(); renderGroupStudentList(); if(state&&state.id===sid){saveState();renderAll();}}
function saveMission(){const g=$('#missionGroup').value; const selected=$$('#missionVerbs option:checked').map(o=>o.value); missions[g]={title:$('#missionTitle').value.trim()||'Misión del día',tense:$('#missionTense').value,mode:$('#missionMode').value,rounds:Math.max(5,Math.min(20,Number($('#missionRounds').value)||10)),target:Math.max(50,Math.min(100,Number($('#missionTarget').value)||80)),verbs:selected,updatedAt:new Date().toISOString()}; saveJSON('verbopolis-missions',missions); renderMissions(); if(state)renderMissionHero(); alert('Misión guardada para '+g);}
function renderMissions(){const entries=Object.entries(missions); $('#missionList').innerHTML=entries.length?entries.map(([g,m])=>`<div class="summary-row"><strong>${escapeHtml(g)} · ${escapeHtml(m.title)}</strong><br><small>${m.tense==='all'?'Todos los tiempos':tenseName(m.tense)} · ${modeLabel(m.mode)} · ${m.rounds} preguntas · objetivo ${m.target}%</small></div>`).join(''):'<div class="callout">Aún no hay misiones configuradas. Si no configuras nada, el alumnado puede entrenar libremente.</div>';}
function renderStudy(){const v=verbs.find(x=>x.inf===$('#verbSelect').value)||verbs[0],tense=$('#tenseSelect').value,mode=$('#memoryMode').value; $('#studyMeta').textContent=`${v.group} · ${tenseName(tense)}`; $('#studyTitle').textContent=v.inf; $('#conjTable').classList.toggle('accessible-table',mode==='big'); $('#conjTable').innerHTML=pronouns.map((p,i)=>{let form=formatForm(v.forms[tense][i],v.inf,mode); if(mode==='cloze'&&(i===1||i===4))form=`<span class="cloze">${v.forms[tense][i]}</span>`; return `<div class="conj-row"><span class="pronoun">${p}</span><span class="form">${form}</span></div>`}).join(''); $('#verbTip').innerHTML=`<strong>Truco:</strong> ${v.tip}`;}
function formatForm(form,inf,mode){if(mode!=='colour')return escapeHtml(form); const root=inf.slice(0,-2); const safe=escapeHtml(form); const idx=normalize(form).indexOf(normalize(root)); if(idx>=0)return `${escapeHtml(form.slice(0,idx))}<span class="root">${escapeHtml(form.slice(idx,idx+root.length))}</span><span class="ending">${escapeHtml(form.slice(idx+root.length))}</span>`; return safe;}
function speakCurrentTable(){const v=verbs.find(x=>x.inf===$('#verbSelect').value)||verbs[0],tense=$('#tenseSelect').value; const text=`${v.inf}, ${tenseName(tense)}. `+pronouns.map((p,i)=>`${p}: ${v.forms[tense][i]}`).join('. '); if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text));}}
function startGame(mode,focusMistakes){if(!state)return; const difficulty=$('#difficultySelect').value; const mission=mode==='mission'?missions[state.group]:null; const finalMode=mission?mission.mode:mode; const isExam=mode==='exam'; game={mode:finalMode,displayMode:mode,difficulty,round:0,max:isExam?12:(mission?.rounds||({easy:8,normal:10,hard:12}[difficulty])),hearts:isExam?1:({easy:4,normal:3,hard:2}[difficulty]),score:0,correct:0,focusMistakes,mission,isExam,results:[]}; $('#gameModeLabel').textContent=(isExam?'Evaluación':modeLabel(mode))+' · '+(focusMistakes?'Repaso de errores':''); $('#feedback').textContent=''; updateHud(); nextQuestion();}
function nextQuestion(){if(game.round>=game.max||game.hearts<=0)return endGame(); game.round++; currentQuestion=makeQuestion(); renderQuestion(currentQuestion); updateHud();}
function makeQuestion(){let pool=verbs,tensePool=tenses; if(game.mission){if(game.mission.verbs?.length)pool=verbs.filter(v=>game.mission.verbs.includes(v.inf)); if(game.mission.tense&&game.mission.tense!=='all')tensePool=tenses.filter(t=>t.id===game.mission.tense);} if(game.focusMistakes&&state.mistakes.length){const m=sample(state.mistakes.slice(0,12)); const verb=verbs.find(v=>v.inf===m.inf)||sample(pool),tense=tenses.find(t=>t.id===m.tense)||sample(tensePool); return buildQuestion(verb,tense,m.person,game.mode==='mixed'?sample(['conjugate','choose','detective']):game.mode);} const verb=sample(pool.length?pool:verbs), tense=sample(tensePool.length?tensePool:tenses), personIndex=Math.floor(Math.random()*6); const qtype=game.mode==='mixed'||game.mode==='mission'?sample(['conjugate','choose','detective']):game.mode; return buildQuestion(verb,tense,personIndex,qtype);}
function buildQuestion(verb,tense,personIndex,type){const answer=verb.forms[tense.id][personIndex]; if(type==='detective')return {type,verb,tense,personIndex,answer:`${verb.inf} · ${tense.name} · ${people[personIndex]}`,prompt:`Analiza la forma verbal: “${answer}”`,context:'Di infinitivo, tiempo y persona'}; if(type==='choose'){const opts=new Set([answer]); while(opts.size<4){opts.add(sample(verbs).forms[tense.id][Math.floor(Math.random()*6)])} return {type,verb,tense,personIndex,answer,options:shuffle([...opts]),prompt:`Elige la forma correcta para: ${pronouns[personIndex]} · ${verb.inf}`,context:tense.name};} return {type:'conjugate',verb,tense,personIndex,answer,prompt:`Conjuga “${verb.inf}” para ${pronouns[personIndex]}`,context:tense.name};}
function renderQuestion(q){let html=`<p class="mini-context">${q.context}</p><p class="prompt">${q.prompt}</p>`; if(q.type==='conjugate'){html+=`<div class="answer-row"><input id="textAnswer" autocomplete="off" placeholder="Escribe la forma verbal" /><button class="primary" id="submitAnswer">Comprobar</button></div>${game.isExam?'':'<button class="ghost small" id="hintBtn">Dame una pista</button><div id="hintBox"></div>'}`;} else {const opts=q.options||makeAnalysisOptions(q); html+=`<div class="options-grid">${opts.map(o=>`<button class="option" data-answer="${escapeHtml(o)}">${escapeHtml(o)}</button>`).join('')}</div>`;} $('#questionArea').className='question-area'; $('#questionArea').innerHTML=html; $('#submitAnswer')?.addEventListener('click',()=>checkText()); $('#textAnswer')?.addEventListener('keydown',e=>{if(e.key==='Enter')checkText()}); $('#hintBtn')?.addEventListener('click',()=>showHint(q)); $$('.option').forEach(b=>b.onclick=()=>checkOption(b)); setTimeout(()=>$('#textAnswer')?.focus(),30);}
function makeAnalysisOptions(q){const opts=new Set([q.answer]); while(opts.size<4){const v=sample(verbs),t=sample(tenses),i=Math.floor(Math.random()*6); opts.add(`${v.inf} · ${t.name} · ${people[i]}`)} return shuffle([...opts]);}
function checkText(){checkAnswer($('#textAnswer').value,currentQuestion.answer)}
function checkOption(btn){$$('.option').forEach(b=>b.disabled=true); const ok=btn.dataset.answer===currentQuestion.answer; btn.classList.add(ok?'correct':'wrong'); if(!ok)$$('.option').find(b=>b.dataset.answer===currentQuestion.answer)?.classList.add('correct'); applyResult(ok,btn.dataset.answer);}
function checkAnswer(given,correct){applyResult(normalize(given)===normalize(correct),given)}
function applyResult(ok,given=''){state.total++; if(ok){state.correct++; state.streak++; state.bestStreak=Math.max(state.bestStreak,state.streak); game.score+=game.isExam?1:10; game.correct++; state.xp+=game.isExam?5:10; if(currentQuestion.verb.group.includes('irregular'))state.irregularCorrect++; feedback(game.isExam?'Respuesta registrada.':'¡Correcto! +10 XP',true); if(!settings.quiet)confetti(8);} else {state.streak=0; game.hearts--; state.mistakes.unshift({inf:currentQuestion.verb.inf,tense:currentQuestion.tense.id,person:currentQuestion.personIndex,correct:currentQuestion.answer,given,at:new Date().toISOString()}); state.mistakes=state.mistakes.slice(0,40); feedback(game.isExam?'Respuesta registrada.':`Casi. Respuesta correcta: ${currentQuestion.answer}`,false);} game.results.push({ok,verb:currentQuestion.verb.inf,tense:currentQuestion.tense.id,person:pronouns[currentQuestion.personIndex]}); queueEvent(game.isExam?'exam_answer':'answer',{group:state.group,mode:game.displayMode||game.mode,difficulty:game.difficulty,round:game.round,verb:currentQuestion.verb.inf,tense:currentQuestion.tense.id,person:pronouns[currentQuestion.personIndex],questionType:currentQuestion.type,correctAnswer:currentQuestion.answer,givenAnswer:given,isCorrect:ok,xp:state.xp,total:state.total,correctTotal:state.correct,streak:state.streak}); saveState(); renderAll(); syncQueue(false); setTimeout(nextQuestion,game.isExam?500:(ok?850:1600));}
function feedback(text,good){const f=$('#feedback'); f.textContent=text; f.className=`feedback ${good?'good':'bad'}`;}
function showHint(q){$('#hintBox').innerHTML=`<span class="tip">Empieza por “${q.answer[0]}”. ${q.verb.tip}</span>`;}
function updateHud(){$('#hearts').textContent='❤️'.repeat(Math.max(0,game.hearts))+'🤍'.repeat(Math.max(0,4-game.hearts)); $('#scoreText').textContent=game.isExam?`${game.correct} aciertos`:`${game.score} puntos`; $('#roundText').textContent=`${Math.min(game.round,game.max)}/${game.max}`;}
function endGame(){const pct=game.max?Math.round((game.correct/game.max)*100):0; const won=game.isExam?pct>=80:game.hearts>0; const note=game.isExam?Math.round((game.correct/game.max)*10*10)/10:null; log(`${game.isExam?'Evaluación':'Reto'}: ${pct}%${note!==null?' · nota '+note:''}`); if(game.isExam&&pct>=80&&!state.badges.includes('exam80'))state.badges.push('exam80'); queueEvent(game.isExam?'exam_finished':'game_finished',{group:state.group,mode:game.displayMode||game.mode,difficulty:game.difficulty,score:game.score,correctInGame:game.correct,roundsPlayed:game.max,percentage:pct,note,heartsLeft:game.hearts,xp:state.xp,accuracy:state.total?Math.round(state.correct/state.total*100):0}); saveState(); syncQueue(false); $('#questionArea').innerHTML=`<div class="empty-state"><span>${won?'🏆':'💪'}</span><p><strong>${game.isExam?`Nota: ${note}/10`:`${game.score} puntos`}</strong><br>${game.isExam?`Aciertos: ${game.correct}/${game.max} (${pct}%).`:(won?'Has conquistado otra zona de Verbópolis.':'Repasa tus errores y vuelve a intentarlo.')}</p><button class="primary" id="againBtn">Jugar otra vez</button></div>`; $('#againBtn').onclick=()=>startGame(game.displayMode||game.mode,game.focusMistakes); renderAll();}
function renderMistakes(){if(!state)return; $('#mistakeList').innerHTML=state.mistakes.length?state.mistakes.slice(0,10).map(m=>`<div class="mistake"><strong>${m.inf}</strong> · ${tenseName(m.tense)} · ${pronouns[m.person]}<br><small>Correcta: ${m.correct}${m.given?` · Respuesta: ${escapeHtml(m.given)}`:''}</small></div>`).join(''):'<div class="mistake">No hay errores pendientes. ¡Buen trabajo!</div>';}
function renderBadges(){if(!state)return; $('#badges').innerHTML=badgeCatalog.map(b=>`<div class="badge-card"><span>${b.icon}</span><strong>${b.name}</strong><br><small>${state.badges.includes(b.id)?'Conseguida':'Pendiente'}</small></div>`).join('');}
function checkBadges(){if(!state)return; const add=idv=>{if(!state.badges.includes(idv))state.badges.push(idv)}; if(state.total>0)add('first'); if(state.bestStreak>=5)add('streak5'); if(state.bestStreak>=10)add('streak10'); if(state.xp>=100)add('xp100'); if(state.irregularCorrect>=10)add('irregular10');}
function renderMap(){if(!state)return; $('#worldMap').innerHTML=zones.map(z=>`<div class="zone ${state.xp>=z.xp?'':'locked'}"><div class="emoji">${z.emoji}</div><strong>${z.name}</strong><p>${z.desc}</p><small>${state.xp>=z.xp?'Desbloqueada':`Necesitas ${z.xp-state.xp} XP más`}</small></div>`).join('');}
function renderStats(){if(!state)return; $('#statXp').textContent=state.xp; $('#statAccuracy').textContent=(state.total?Math.round(state.correct/state.total*100):0)+'%'; $('#statStreak').textContent=state.bestStreak;}
function log(text){state.log.unshift({text,at:new Date().toLocaleString('es-ES')}); state.log=state.log.slice(0,12);}
function renderLog(){if(!state)return; $('#activityLog').innerHTML=state.log.length?state.log.map(l=>`<div class="log-item"><strong>${escapeHtml(l.text)}</strong><br><small>${l.at}</small></div>`).join(''):'<div class="log-item">Aún no hay actividad.</div>';}
function renderClassSummary(){const rows=students.map(s=>getStudentState(s.id)).sort((a,b)=>b.xp-a.xp); $('#classSummary').innerHTML=rows.map((s,i)=>`<div class="summary-row"><strong>${i+1}. ${s.avatar} ${escapeHtml(s.name)}</strong><br><small>${escapeHtml(s.group||'')} · ${s.xp} XP · ${s.total?Math.round(s.correct/s.total*100):0}% acierto · mejor racha ${s.bestStreak}</small></div>`).join(''); renderTeacherRadar(rows);}
function renderTeacherRadar(rows){const tenseErrors={}; const verbErrors={}; rows.forEach(s=>s.mistakes.forEach(m=>{tenseErrors[m.tense]=(tenseErrors[m.tense]||0)+1; verbErrors[m.inf]=(verbErrors[m.inf]||0)+1;})); const low=rows.filter(s=>s.total>=5&&s.correct/s.total<.6); const best=rows[0]; $('#teacherRadar').innerHTML=`<div class="radar-item"><strong>Tiempo más fallado</strong><p>${topKey(tenseErrors,tenseName)||'Aún sin datos'}</p></div><div class="radar-item"><strong>Verbo más fallado</strong><p>${topKey(verbErrors,x=>x)||'Aún sin datos'}</p></div><div class="radar-item"><strong>Necesitan repaso</strong><p>${low.length?low.map(s=>escapeHtml(s.name)).join(', '):'Nadie con datos suficientes'}</p></div><div class="radar-item"><strong>Ranking por avatares</strong><p>${rows.slice(0,5).map(s=>`${s.avatar} ${s.xp}XP`).join(' · ')||'Sin datos'}</p></div>`;}
function topKey(obj,label){const e=Object.entries(obj).sort((a,b)=>b[1]-a[1])[0]; return e?`${label(e[0])} (${e[1]} errores)`:'';}
function renderSyncPanel(){const el=$('#syncPanel'); if(!el)return; el.innerHTML=`<div class="sync-item"><strong>${settings.backendUrl?'Conectado a Google Sheets':'Sin conexión a Google Sheets'}</strong><br><small>${queue.length} evento(s) pendientes de enviar. Último sync: ${state?.lastSync||'—'}</small></div>`; if($('#cloudState'))$('#cloudState').textContent=settings.backendUrl?`☁️ ${queue.length} envío(s) pendientes`:'💾 Modo local';}
function queueEvent(type,data={}){const payload={eventId:crypto.randomUUID?crypto.randomUUID():id(),type,createdAt:new Date().toISOString(),classCode:settings.classCode||'',studentId:state?.id||data.studentId||'',studentName:state?.name||data.studentName||'',group:state?.group||data.group||'',avatar:state?.avatar||data.avatar||'',data}; queue.push(payload); queue=queue.slice(-600); saveJSON('verbopolis-sync-queue',queue); renderSyncPanel();}
function syncQueue(force){if(!settings.backendUrl||!queue.length){renderSyncPanel();return} const batch=queue.slice(0,25); const body={action:'logBatch',classCode:settings.classCode||'',events:batch}; fetch(settings.backendUrl,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)}).then(()=>{queue=queue.slice(batch.length); saveJSON('verbopolis-sync-queue',queue); if(state){state.cloudSaves=(state.cloudSaves||0)+batch.length; state.lastSync=new Date().toLocaleString('es-ES'); saveState()} renderSyncPanel(); if(force&&queue.length)setTimeout(()=>syncQueue(true),500);}).catch(()=>{if(force)alert('No se ha podido enviar. Se queda guardado en la cola local.')});}
function jsonp(action,params,onOk,onErr){if(!settings.backendUrl)return onErr&&onErr(); const cb='verbopolis_cb_'+Date.now(); const script=document.createElement('script'); const url=new URL(settings.backendUrl); url.searchParams.set('action',action); url.searchParams.set('callback',cb); Object.entries(params||{}).forEach(([k,v])=>url.searchParams.set(k,v)); window[cb]=res=>{delete window[cb];script.remove();onOk&&onOk(res)}; script.onerror=()=>{delete window[cb];script.remove();onErr&&onErr()}; script.src=url.toString(); document.body.appendChild(script);}
function exportAllCsv(){const rows=[['grupo','alumno','xp','aciertos','intentos','porcentaje','mejor_racha','errores']]; students.forEach(s=>{const st=getStudentState(s.id); rows.push([st.group,st.name,st.xp,st.correct,st.total,st.total?Math.round(st.correct/st.total*100):0,st.bestStreak,st.mistakes.length])}); downloadCsv('verbopolis-aula-local.csv',rows);}
function downloadCsv(name,rows){const csv=rows.map(r=>r.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(',')).join('\n'); const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url);}
function createWorksheet(){const mission=state?missions[state.group]:null; const qs=[]; const pool=mission?.verbs?.length?verbs.filter(v=>mission.verbs.includes(v.inf)):verbs; const tensePool=mission?.tense&&mission.tense!=='all'?tenses.filter(t=>t.id===mission.tense):tenses; for(let i=0;i<10;i++){qs.push({v:sample(pool),t:sample(tensePool),p:Math.floor(Math.random()*6)})} $('#worksheet').innerHTML=`<h4>Ficha rápida: misión verbal</h4><p>Nombre: __________________ Grupo: ______ Fecha: ____________</p><ol>${qs.map(q=>`<li>Conjuga <strong>${q.v.inf}</strong> en <strong>${q.t.name}</strong>, persona <strong>${pronouns[q.p]}</strong>: __________________</li>`).join('')}</ol><p><strong>Reto extra:</strong> escribe una oración con tres formas verbales distintas y subraya el verbo.</p>`;}
function modeLabel(m){return {mission:'Misión del grupo',mixed:'Mixto',conjugate:'Conjugar',choose:'Elegir',detective:'Detective verbal',exam:'Evaluación'}[m]||m;}
function tenseName(idv){return tenses.find(t=>t.id===idv)?.name||idv} function sample(arr){return arr[Math.floor(Math.random()*arr.length)]} function shuffle(arr){return [...arr].sort(()=>Math.random()-.5)} function normalize(s){return(s||'').toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ')} function escapeHtml(str){return String(str??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))} function id(){return 'id-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8)}
function loadJSON(k,fallback){try{const v=localStorage.getItem(k);return v?JSON.parse(v):fallback}catch{return fallback}} function saveJSON(k,v){localStorage.setItem(k,JSON.stringify(v))}
function confetti(n=18){for(let i=0;i<n;i++){const c=document.createElement('div'); c.className='confetti'; c.textContent=sample(['⭐','✨','🎉','🟡','🟢']); c.style.left=Math.random()*100+'vw'; c.style.animationDelay=Math.random()*.25+'s'; document.body.appendChild(c); setTimeout(()=>c.remove(),2200);}}
boot();
